sudo: required
language: generic

services:
    - docker

before_install:
  - docker build -t lerolynn/docker-react -f Dockerfile.dev .
  
script:
  - docker run -e CI=true lerolynn/docker-react npm run test
