sudo: required
language: generic

services:
    - docker

before_install:
  - docker build -t lerolynn/docker-react -f Dockerfile.dev .
  
script:
  - docker run -e CI=true lerolynn/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker"
  end: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-2-073278436360"
  bucket_path: "docker"
  on: 
    branch: master

access_key_id: $AWS_ACCESS_KEY
secret_access_key: $AWS_SECRET_KEY